name: Publish GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  # pull_request:
  #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: chmod x *.sh
      run: chmod +x *.sh
    - name: make html
      run: make index.html;make style.css
      timeout-minutes: 60
    - name: Generate PNG Diagrams
      uses: hokorobi/plantuml-github-action@main
      continue-on-error: true
      with:
        args: -v -tpng uml/*.uml
    - name: mkdir
      run: mkdir -p publish/uml
    - name: copy to dir
      run: cp -r index.html style.css uml publish

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish

